=== wiepke/competence-database/competence-database/src/main/scala/resources/imsrdceo_rootv1p0.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns="http://www.imsglobal.org/xsd/imsrdceo_rootv1p0" targetNamespace="http://www.imsglobal.org/xsd/imsrdceo_rootv1p0" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:annotation>
		<xs:documentation>
			IPR, License and Distribution Notices
			This machine readable file is derived from IMS specification IMS Reusable Definition of Competency or 
			Educational Objective - XML Binding Version 1.0 Final Specification found at 
			http://www.imsglobal.org/competences/ and the original IMS schema binding or code base
			http://www.imsglobal.org/competences/rdceov1p0/imsrdceo_bindv1p0.html.
			
			Recipients of this document are requested to submit, with their comments, notification of any relevant patent 
			claims or other intellectual property rights of which they may be aware that might be infringed by the schema 
			binding contained in this document.
			
			IMS takes no position regarding the validity or scope of any intellectual property or other rights that might be 
			claimed to pertain to the implementation or use of the technology described in this document or the extent to 
			which any license under such rights might or might not be available; neither does it represent that it has made 
			any effort to identify any such rights. Information on IMS's procedures with respect to rights in IMS specifications 
			can be found at the IMS Intellectual Property Rights web page: http://www.imsglobal.org/ipr/imsipr_policyFinal.pdf.
			
			Copyright (c) IMS Global Learning Consortium 1999-2007. All Rights Reserved.
			
			License Notice for Users
			Users of products or services that include this document are hereby granted a worldwide, royalty-free, 
			non-exclusive license to use this document.
			
			Distribution Notice for Developers
			Developers of products or services that provide distribution of this document as is or with modifications are 
			required to register with the IMS community on the IMS website as described in the following two paragraphs:
			
			- If you wish to distribute this document as is, with no modifications, you are hereby granted permission to copy, 
			display and distribute the contents of this document in any medium for any purpose without fee or royalty provided 
			that you include this IPR, License and Distribution notice in its entirety on ALL copies, or portions thereof, that you 
			make and you complete a valid license registration with IMS and receive an email from IMS granting the license. 
			To register, follow the instructions on the IMS website: http://www.imsglobal.org/specificationdownload.cfm. Once 
			registered you are granted permission to transfer unlimited distribution rights of this document for the purposes 
			of third-party or other distribution of your product or service that incorporates this document as long as this IPR, 
			License and Distribution notice remains in place in its entirety.
			
			- If you wish to create and distribute a derived work from this document, you are hereby granted permission to copy, 
			display and distribute the contents of the derived work in any medium for any purpose without fee or royalty provided 
			that you include this IPR, License and Distribution notice in its entirety on ALL copies, or portions thereof, that you 
			make and you complete a valid profile registration with IMS and receive an email from IMS granting the license. To 
			register, follow the instructions on the IMS website: http://www.imsglobal.org/profile/. Once registered you are 
			granted permission to transfer unlimited distribution rights of the derived work for the purposes of third-party or 
			other distribution of your product or service that incorporates the derived work as long as this IPR, License and 
			Distribution notice remains in place in its entirety.
			
			The limited permissions granted above are perpetual and will not be revoked by IMS or its successors or assigns.
			
			THIS SPECIFICATION IS BEING OFFERED WITHOUT ANY WARRANTY WHATSOEVER, AND IN PARTICULAR, 
			ANY WARRANTY OF NONINFRINGEMENT IS EXPRESSLY DISCLAIMED. ANY USE OF THIS SPECIFICATION 
			SHALL BE MADE ENTIRELY AT THE IMPLEMENTER'S OWN RISK, AND NEITHER THE CONSORTIUM, NOR 
			ANY OF ITS MEMBERS OR SUBMITTERS, SHALL HAVE ANY LIABILITY WHATSOEVER TO ANY IMPLEMENTER 
			OR THIRD PARTY FOR ANY DAMAGES OF ANY NATURE WHATSOEVER, DIRECTLY OR INDIRECTLY, ARISING 
			FROM THE USE OF THIS SPECIFICATION.	
		</xs:documentation>
	</xs:annotation>
	<xs:group name="extelement">
		<xs:annotation>
			<xs:documentation>extension mechanism for elements</xs:documentation>
		</xs:annotation>
		<xs:sequence>
			<xs:any namespace="##other" processContents="strict" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:group>
	<xs:element name="rdceo">
		<xs:annotation>
			<xs:documentation>A single definition of a competence, educational objective etc</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="identifier" minOccurs="1" maxOccurs="1"/>
				<xs:element ref="title"/>
				<xs:element ref="description" minOccurs="0"/>
				<xs:element ref="definition" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element ref="metadata" minOccurs="0"/>
				<xs:sequence minOccurs="0">
					<xs:group ref="extelement"/>
				</xs:sequence>
			</xs:sequence>
			<xs:anyAttribute namespace="##other" processContents="strict"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="langstring">
		<xs:annotation>
			<xs:documentation>A string in a human language</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:string">
					<xs:anyAttribute namespace="##other" processContents="strict"/>
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="title">
		<xs:annotation>
			<xs:documentation>A title for the definition</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="langstring" maxOccurs="unbounded"/>
				<xs:sequence minOccurs="0">
					<xs:group ref="extelement"/>
				</xs:sequence>
			</xs:sequence>
			<xs:anyAttribute namespace="##other" processContents="strict"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="identifier">
		<xs:annotation>
			<xs:documentation>Catenated form of the identifier of a RDCEO</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:anyURI">
					<xs:anyAttribute namespace="##other" processContents="strict"/>
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<xs:annotation/>
	<xs:element name="description">
		<xs:annotation>
			<xs:documentation>A description for the definition</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="langstring" maxOccurs="unbounded"/>
				<xs:sequence minOccurs="0">
					<xs:group ref="extelement"/>
				</xs:sequence>
			</xs:sequence>
			<xs:anyAttribute namespace="##other" processContents="strict"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="definition">
		<xs:annotation>
			<xs:documentation>A structured form of the definition</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="model" minOccurs="0"/>
				<xs:element ref="statement" maxOccurs="unbounded"/>
				<xs:sequence minOccurs="0">
					<xs:group ref="extelement"/>
				</xs:sequence>
			</xs:sequence>
			<xs:anyAttribute namespace="##other" processContents="strict"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="model">
		<xs:annotation>
			<xs:documentation>The model identification for the structured definition</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:string">
					<xs:anyAttribute namespace="##other" processContents="strict"/>
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="statement">
		<xs:annotation>
			<xs:documentation>A component part of a structured definition</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:choice>
					<xs:element ref="statementtext"/>
					<xs:element ref="statementtoken"/>
				</xs:choice>
				<xs:sequence minOccurs="0">
					<xs:group ref="extelement"/>
				</xs:sequence>
			</xs:sequence>
			<xs:attribute name="statementid" type="xs:ID"/>
			<xs:attribute name="statementname" type="xs:string"/>
			<xs:anyAttribute namespace="##other" processContents="strict"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="statementtext">
		<xs:annotation>
			<xs:documentation>Used for statements with free-form text</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="langstring" maxOccurs="unbounded"/>
				<xs:sequence minOccurs="0">
					<xs:group ref="extelement"/>
				</xs:sequence>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="source">
		<xs:annotation>
			<xs:documentation>Source identification for a vocabulary token</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:string">
					<xs:anyAttribute namespace="##other" processContents="strict"/>
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="value">
		<xs:annotation>
			<xs:documentation>A vocabulary token</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:string">
					<xs:anyAttribute namespace="##other" processContents="strict"/>
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="metadata">
		<xs:annotation>
			<xs:documentation>A container for metadta</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="rdceoschema" minOccurs="0"/>
				<xs:element ref="rdceoschemaversion" minOccurs="0"/>
				<xs:sequence minOccurs="0">
					<xs:group ref="extelement"/>
				</xs:sequence>
			</xs:sequence>
			<xs:anyAttribute namespace="##other" processContents="strict"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="statementtoken">
		<xs:annotation>
			<xs:documentation>Used for statements with token values (vocabulary use)</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="source"/>
				<xs:element ref="value"/>
				<xs:sequence minOccurs="0">
					<xs:group ref="extelement"/>
				</xs:sequence>
			</xs:sequence>
			<xs:anyAttribute namespace="##other" processContents="strict"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="rdceoschema">
		<xs:annotation>
			<xs:documentation>The identity of the RDCEO schema - assumed to be IMS RDCEO if absent.</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:string">
					<xs:anyAttribute namespace="##other" processContents="strict"/>
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="rdceoschemaversion">
		<xs:annotation>
			<xs:documentation>The version of the RDCEO schema - assumed to be 1.0 if absent</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:string">
					<xs:anyAttribute namespace="##other" processContents="strict"/>
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== wiepke/competence-database/competence-database/src/main/scala/resources/imsrdceo_rootv1p0.xml
<?xml version="1.0" encoding="UTF-8"?>
<p:rdceo xmlns:p="http://www.imsglobal.org/xsd/imsrdceo_rootv1p0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.imsglobal.org/xsd/imsrdceo_rootv1p0 imsrdceo_rootv1p0.xsd ">
  <p:identifier>http://tempuri.org</p:identifier>
  <p:title>
    <p:langstring>BeispielKompetenz</p:langstring>
  </p:title>
  <p:description>
    <p:langstring>Entscheidende Struktur der Beispielkompetenz</p:langstring>
  </p:description>
  <p:definition>
    <p:model>Kompetenzmodell</p:model>
    <p:statement statementid="idvalue0" statementname="">
      <p:statementtext>
        <p:langstring>Wissen</p:langstring>
        <p:langstring>Anwendungskontext</p:langstring>
        <p:langstring>Überprüfbarkeit</p:langstring>
        <p:langstring>Teilkompetenzen</p:langstring>
        <p:langstring>Teilerfolge</p:langstring>
      </p:statementtext>
    </p:statement>
  </p:definition>
  <p:metadata>
    <p:rdceoschema>p:rdceoschema</p:rdceoschema>
    <p:rdceoschemaversion>p:rdceoschemaversion</p:rdceoschemaversion>
  </p:metadata>
</p:rdceo>
